# Profile information
name: Recruiting
title: Recruiting
description: > # this means to ignore newlines until "baseurl:"
  Job hunting can be overwhelming. This site aims to give advice on job hunting for software engineering internships/jobs.
permalink: ':title/'

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: shannonphu

# Contact form
email: shannonphu@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
